### ISSUE TITLE
Version in attributes not taking effect

### ISSUE THREAD

**Issue by Gary-Armstrong** [rabbitmq/chef-cookbook#361]
Long week, might be me, but pretty sure I'm doing it correctly.
In my attributes/rmq.rb:

```
default['rabbitmq']['version'] = '3.5.6-1'
```

Then I'm running the recipe on a CentOS 6.6 and I see:

```
  * rpm_package[/var/chef/cache/rabbitmq-server-3.6.1-1.noarch.rpm] action install
```

This doesn't really hurt my feelings, except for:

```
    error: Failed dependencies:
        erlang >= R16B-03 is needed by rabbitmq-server-3.6.1-1.noarch
```

Which is a bit much for a Friday afternoon.  Anyway, I think I followed the directions and the recipe attributes look like what I am using.  You can tell me I'm doing something dumb, I don't mind.

**Comment by Gary-Armstrong** [comment]
I made this work my backing down to rabbitmq v4.6.0, so yay?

**Comment by isuftin** [comment]
Looks like on CentOS 6.7 bento box version 2.2.5, the latest version I've got for rabbitmq-server is 3.1.5-1.el6

I left the attributes at default for this cookbook and am seeing:

```
Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of rpm  -i /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm ----
           STDOUT:
           STDERR: warning: /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID 056e8e56: NOKEY
           error: Failed dependencies:
                erlang >= R16B-03 is needed by rabbitmq-server-3.6.1-1.noarch
           ---- End output of rpm  -i /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm ----
           Ran rpm  -i /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm returned 1
```

**Comment by isuftin** [comment]
With 2.2.6 installed, it seems like it's still not meeting dependency requirements. 

```
$ yum info erlang
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.tripadvisor.com
 * epel: mirror.csclub.uwaterloo.ca
 * extras: mirror.atlantic.net
 * updates: centos.netnitco.net
Installed Packages
Name        : erlang
Arch        : x86_64
Version     : R14B
Release     : 04.3.el6
Size        : 31 k
Repo        : installed
From repo   : epel
Summary     : General-purpose programming language and runtime environment
URL         : http://www.erlang.org
License     : ERPL
Description : Erlang is a general-purpose programming language and runtime
            : environment. Erlang has built-in support for concurrency, distribution
            : and fault tolerance. Erlang is used in several large telecommunication
            : systems from Ericsson.
```

**Comment by Gary-Armstrong** [comment]
I had believed that not setting distro_version would get from rabbitmq.com in all cases.  It did work previously using distro_version but I would then get different results from yum mirrors (entirely different problem that I did not have time or smarts to resolve).  I probably want to use rabbitmq.com as source anyway.

**Comment by thedrow** [comment]
Even if you don't set distro_version, you can't install a specified rabbitmq version from their repository.
We specified 3.6.2 but we still got 3.6.1.
See https://github.com/jjasghar/rabbitmq/blob/master/recipes/default.rb#L63
The version attribue is never specified anywhere.

**Comment by michaelklishin** [comment]
RabbitMQ apt repo only provides a single version. [Package Cloud](https://packagecloud.io/rabbitmq) provides a few most recent releases.

**Comment by johngun3** [comment]
I just ran into this on ubuntu. I believe the issue is due to the `deb_package` and `deb_package_url` attributes being defined with `#{node['rabbitmq']['version']}` in the attributes file. I think any "compound" attributes assignments that rely on other attribute values via string interpolation should be defined in the recipe itself to give the user the opportunity to override the values.

**Comment by adhodgson1** [comment]
I have the same issue and confirm it is due to the default attributes file in the cookbook referring to the version attribute for the RPM location.  In my case I fixed it by creating the following attributes:

node.normal['erlang']['install_method'] = 'esl'
node.normal['rabbitmq']['version'] = '3.6.10'
node.normal['rabbitmq']['rpm_package_url'] = 'https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.10/'
node.normal['rabbitmq']['rpm_package'] = 'rabbitmq-server-3.6.10-1.el7.noarch.rpm'

It is necessary to set the 3 attributes as version is used in other recipes.

I suggest the fix is to move the logic for getting the RPM package URL and name to the recipe rather than the attributes file.

Andrew.

**Comment by michaelklishin** [comment]
There is a doc section about custom download locations. Most users need to simply specify a version.
