### ISSUE TITLE
systemd script

### ISSUE THREAD

**Issue by rleibman** [rabbitmq/chef-cookbook#389]
For centos/redhat 7 you should be using systemd instead of init.d scripts, a typical script should look like this:
# systemd unit example

[Unit]
Description=RabbitMQ broker
After=network.target 
Wants=network.target 

[Service]
Type=notify
User=rabbitmq
Group=rabbitmq
Restart=always
SyslogIdentifier=rabbitmq
LimitNOFILE=65536
NotifyAccess=all
TimeoutStartSec=3600
WorkingDirectory=/var/lib/rabbitmq
ExecStart=/usr/sbin/rabbitmq-server
ExecStop=/usr/sbin/rabbitmqctl stop

[Install]
WantedBy=multi-user.target

**Comment by michaelklishin** [comment]
As of 3.6.3, RabbitMQ includes systemd scripts in Debian and RPM packages.

**Comment by rleibman** [comment]
So... how do I enable it in the recipe?

**Comment by ohadedel** [comment]
+1 on the question

**Comment by michaelklishin** [comment]
systemd is suppoted by the Debian package as of https://github.com/rabbitmq/rabbitmq-server/issues/570, CentOS/Fedora/RHEL will follow in https://github.com/rabbitmq/rabbitmq-server/issues/932.

You can configure [what URL .deb is downloaded from](https://github.com/rabbitmq/chef-cookbook/blob/master/recipes/default.rb#L58).

**Comment by rmldsky** [comment]
Hm, still I guess, despite the presence of the script in the package itself, this cookboook would need a bit of tweaking due to `node['rabbitmq']['job_control']` attribute. In `default` recipe there is an `if` clause additionally checking for `upstart` and removing init.d script plus creating one for `upstart`. If rabbitmq system package already comes with service script it would be nice to default to those in the cookbook and/or have it supported (via templating). For now cookbook only supports `initd` and `upstart`.

**Comment by michaelklishin** [comment]
@rmldsky fair enough, that's why this issue is open :)

**Comment by jgoldschrafe** [comment]
As an interim workaround, you should be able to force `node['rabbitmq']['job_control']` to `upstart` and `node['rabbitmq']['manage_service']` to `false` to completely disable the cookbook's attempts to manage the service, allowing you to handle this yourself in your wrapper cookbook.

**Comment by majormoses** [comment]
I will see about adding support for systemd.

**Comment by michaelklishin** [comment]
Both RPM and Debian RabbitMQ packages now support systemd.
