### ISSUE TITLE
How can i pass user variables from data bags to rabbitmq_user resource?

### ISSUE THREAD

**Issue by vamsivv** [rabbitmq/chef-cookbook#398]
Hi, Please let me know how can i pass user details as array to rabbitmq_user resource?

**Comment by devsibwarra** [comment]
@vamsivv Using a wrapper cookbook is probably the best solution here.

Example environment (or role/node settings)
```json
                "rabbitmq": {
                        "enabled_users": [
                                {
                                        "name": "guest",
                                        "password": "guest",
                                        "tag": "administrator",
                                        "rights": [
                                                {
                                                        "vhost": null,
                                                        "conf": ".*",
                                                        "write": ".*",
                                                        "read": ".*"
                                                }
                                        ]
                                },
                                {
                                        "name": "ops",
                                        "password": "DATA_BAG",
                                        "tag": "administrator",
                                        "rights": [ ... ]
                                },
                                {
                                        "name": "shovel",
                                        "password": "DATA_BAG",
                                        "rights": [ ... ]
                                }
                        ]
                }
```

In the wrapper cookbook I could then use
```ruby
  databag_secret = Chef::EncryptedDataBagItem.load_secret(node['encrypted_data_bag_secret_key_path'])
  user_secrets = Chef::EncryptedDataBagItem.load('rabbitmq', 'users', databag_secret)
  node.force_override!['rabbitmq']['enabled_users'] = node['rabbitmq']['enabled_users'].to_a.each { |x| x['password'] = user_secrets["user_#{x['name']}"] if x['password'] == 'DATA_BAG' }
```

Define a password for the ops user by creating a key `user_ops` in the data bag `rabbitmq` attr `users`

**Comment by GitBytes** [comment]
Hey @vamsivv,

Put together a fun little trick here utilizing the Chef's deepmerge mixin:
```
rabbitmq_data = []
node['cookbook']['vhosts'].each do |vhost|
  vhost_data = data_bag_item(data_bag, vhost)
  if vhost_data.key?('rabbitmq')
    rabbitmq_data = Chef::Mixin::DeepMerge.merge(vhost_data['rabbitmq'], rabbitmq_data)
  end
end
node.default['rabbitmq'] = Chef::Mixin::DeepMerge.merge(rabbitmq_data, node['rabbitmq'])
include_recipe 'rabbitmq::user_management'
```

Hopefully this is also a working solution for you. Been very useful for us in creating a scalable rabbitmq user/vhost config based on whatever we put into multiple rabbitmq databag key(s). Cheers!

**Comment by isuftin** [comment]
One question here: Wouldn't these methods cause those passwords to appear in node descriptions both on the Chef server UI as well as via knife?

At the end of your run, wouldn't you want to remove those secrets from node['rabbitmq']['enabled_users'] ?

**Comment by michaelklishin** [comment]
A more secure idea is to [use import definitions](https://github.com/rabbitmq/chef-cookbook/pull/472).

**Comment by isuftin** [comment]
@michaelklishin It's unclear how using importing definitions helps here? Do you have an example for how that would work within the rabbitmq_resource recipe?

**Comment by GitBytes** [comment]
@isuftin Correct, I was just offering up a solution that fit within the described condition and one that, in my case (at the time), was reasonable/good enough (TIMTOWTDI). I would say yes, if you are concerned about the viability of those attributes in the node object in your particular environment, using `import definitions` as suggested by @michaelklishin would provide a way to securely place a file with content from a chef-vault or encrypted data bag then import those settings with normal rabbitmq management plugin features. However, then if that is the only/best/secure way to do it then using the provided attribute method might be considered by definition obsolete since you can fit each configuration within that definition file, if I understand correctly (just enough rope to hang yourself there I guess, j/k). Also, you were looking for additional information on his suggestion, please check out this section of the [README](https://github.com/rabbitmq/chef-cookbook/blob/5d276a422acab4442781ce2033b08e7a06cea5a3/README.md#definitions-import) which also explains the Management Plugin and how to get it installed. I hope that kind of clears up where my suggestion was angled from and wish you well in getting the `import definitions` feature up and running. I am thinking a combination of the deep merge alongside making the file with the configs securely might be able to give you the ability to use multiple vaults/encrypted data bags and still get the single file to satisfy the `import definitions` requirements.. Anyhow, cheers!
