### ISSUE TITLE
Cluster join is failing

### ISSUE THREAD

**Issue by raju-divakaran** [rabbitmq/chef-cookbook#421]
Hello,

I am trying to make a cluster of three nodes, but at the join action its failing

`    ================================================================================
    Error executing action `join` on resource 'rabbitmq_cluster[{"name"=>"rabbit@rabbit1", "type"=>"disc"}, {"name"=>"rabbit@rabbit2", "type"=>"disc"}, {"name"=>"rabbit@rabbit3", "type"=>"disc"}]'
    ================================================================================

    JSON::ParserError
    -----------------
    757: unexpected token at ', {"name":"rabbit@rabbit2", "type":"disc"}, {"name":"rabbit@rabbit3", "type":"disc"}'
`

Maybe anyone else faced the same, please help!

Thanks,
Raju.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Something (possibly Chef) could not parse a JSON file. That's about as much as can be suggested with the amount of information provided.
