### ISSUE TITLE
Separete recipes for installation and file configuration

### ISSUE THREAD

**Issue by LdmlD** [rabbitmq/chef-cookbook#431]
I wanted to use your cookbook for installation of rabbitmq-server. But I need to use rabbitmq-autocluster plugin (https://github.com/aweber/rabbitmq-autocluster). And there is my problems started. Your default cookbook consists rabbitmq-server installation and configuration files managing at the same time. I need some specific configuration for autocluster plugin which not provide in your config files. That's why I can't use your cookbook and need to rewrite all process of installation. 
So maybe there is a good idea to separate processes of installation and file configuration in different recipes?

**Comment by michaelklishin** [comment]
@LdmlD this is an open source project. If you find something missing, you can contribute it instead of asking the maintainers to do it.

This cookbook targets vanilla RabbitMQ. rabbitmq-autocluster support can be added in a separate recipe but we won't make drastic changes to this cookbook if that proves difficult. The reason is this: rabbitmq-autocluster will become largely irrelevant once RabbitMQ 3.7.0 is out because most of its ideas and one backend (DNS) were integrated into RabbitMQ master. So it will be a collection of specific plugins you install, not much else.

And, by the way, you probably want to use the autocluster release from github.com/rabbitmq/rabbitmq-autocluster and not AWeber.

**Comment by michaelklishin** [comment]
For now I'd recommend forking this cookbook and adapting it to support rabbitmq-autocluster. If it goes well, we may consider it. Otherwise you'd simply go on using your fork until RabbitMQ 3.7.0 ships and is supported by this cookbook.
