### ISSUE TITLE
cluster_name is not being set

### ISSUE THREAD

**Issue by amulyas** [rabbitmq/chef-cookbook#460]
even though I have cluster_name attribute set its not setting the cluster name but being defaulted to fiest node in auto clusturing mode

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
@amulyas if you are looking for help, consider providing enough details for the maintainers to work with. Sorry but otherwise they can't help and you are wasting their time.

**Comment by amulyas** [comment]
Issue: cluster_name is not bring set even when I am setting in my cookbook wrapper here is the code 
```  node.override['rabbitmq']['clustering']['enable'] = true
  node.override['rabbitmq']['clustering']['use_auto_clustering'] = true
  node.override['rabbitmq']['clustering']['cluster_name'] = "#{service_uid}-#{service_instance_id}"
  node.override['rabbitmq']['clustering']['cluster_nodes'] = nodes.map do |n|
    { 'name' => "#{node['rabbitmq']['nodename']}@#{n}", 'type' => 'disc' }
```

on chef attributes, I can see the variable is being set correctly 
![image](https://user-images.githubusercontent.com/3798048/30671921-543231a2-9e1e-11e7-9d2e-3a4869e15e96.png)

but on the rabbit node the cluster name was set to default which is one node name whoever comes first 7befa8d3-d322-490d-ba42-e912d7624593@ip-172-51-96-100 

I tried to look at the code where cluster name is being set from attribute was not able to find it . 

below custom resource, set_cluster_name action works properly but attribute way is not working 
rabbitmq_cluster '_' do
  cluster_name "#{service_uid}-#{service_instance_id}"
  action :set_cluster_name
  only_if { clustered }
end

@michaelklishin I am happy to provide more information but I think its cookbook issue, not RMQ issue

**Comment by amulyas** [comment]
@jjasghar see above

**Comment by michaelklishin** [comment]
@amulyas there is no need to ping each maintainer individually. We get the notifications, even after hours, on weekends and so on. I asked before that questions and investigations are posted to the mailing list (most recently here and also in #455). Please cooperate since you are asking for our time without paying us a penny, or feel free to debug your deployment on your own : you have the source code and all the details.

I am locking this because to me personally this privileged behavior is disrespectful.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/55Sve1uty3M)
