### ISSUE TITLE
Cookbbook not starting the management console

### ISSUE THREAD

**Issue by emrprasad** [rabbitmq/chef-cookbook#503]
* Cookbook version used 
Latest - 5.6.1
* Operating system, version, and patch level
Centos 7
* RMQ
3.7.10

I have used:
```
include_recipe 'rabbitmq'
include_recipe 'rabbitmq::mgmt_console'
rabbitmq_plugin "rabbitmq_management" do
  action :enable
end

rabbitmq_plugin "rabbitmq_management_agent" do
  action :enable
end

rabbitmq_plugin "rabbitmq_federation_management" do
  action :enable
end
```
The management plugin is still not enabled, via a chef-run, and I have to manually enable it logging into the nodes. 

Whats the right way to get the plugin started?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest much without Chef client run logs. The `rabbitmq::mgmt_console` recipe [does enable the plugin](https://github.com/rabbitmq/chef-cookbook/blob/v5.x/recipes/mgmt_console.rb#L27). RabbitMQ will log when a plugin is enabled, disabled and started.

**Comment by pvandervelde** [comment]
We might be seeing the same thing as well. I've posted on the google group: https://groups.google.com/forum/#!topic/rabbitmq-users/7RehYWW4Mf8

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/chef-cookbook/commit/697a5e591abc256e8d7789b6ad1389d7f39027d7.
