### ISSUE TITLE
Cloudsmith url points to non-existing binary

### ISSUE THREAD

**Issue by nikolawannabe** [rabbitmq/chef-cookbook#575]
Testing out 5.9.0 as requested, had the following error:
```
==> default: * remote_file[/var/chef/cache/rabbitmq-server_3.8.1-1_all.deb] action create_if_missing
==> default: [2021-06-16T13:50:49-07:00] WARN: remote_file[/var/chef/cache/rabbitmq-server_3.8.1-1_all.deb] cannot be downloaded from https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server-all/raw/versions/3.8.1/rabbitmq-server_3.8.1-1_all.deb: 404 "Not Found"
==> default:     
```

* Cookbook version used: `5.9.0`
* Operating system, version, and patch level
```
vagrant@dev:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
* Node attributes
```
node.default['rabbitmq']['erlang']['enabled'] = true# Debian
node.default['rabbitmq']['erlang']['version'] = '1:23.3.4.3-1'
```
(Note: rabbitmq does not install by default on this version of ubuntu without specifying the version of erlang.  I have no attachment to this specific version.)
* RabbitMQ version provisioned
unspecified, received 3.8.1-1 according to error above
* Erlang version provisioned
1:23.3.4.3-1 as that's what was listed in the instructions
* RabbitMQ server and client application log files
N/A
* Brief instructions that can be used to reproduce the issue e.g. with Vagrant and `chef-solo`
`vagrant destroy && vagrant up` with this version of ubuntu and this version of rabbit cookbook and specified node flags

**Comment by michaelklishin** [comment]
Cloudsmith doesn't have the entire version catalog and the "direct download" repo starts with `3.8.14`. These direct downloads can use GitHub which has everything starting with 3.6.x or so.

I don't know where `3.8.1` may be coming from. Grep doesn't reveal it being used anywhere. `3.8.17` is the default version.
Ubuntu 18.04 with backports [provides `3.8.2`](https://packages.ubuntu.com/search?keywords=rabbitmq-server&searchon=names&suite=bionic-backports&section=all).

Can you please try provisioning `3.8.17` as `3.8.1` is a tad [out of date](https://www.rabbitmq.com/changelog.html)?

**Comment by nikolawannabe** [comment]
Yes, it works if I specify 3.8.17. (I found a spot where a defunct coworker had specified an old version outside of our regular recipe.)  I did have to change some things related to the definition file drop, but for the first time in a while, rabbit installed.  Thanks!

**Comment by michaelklishin** [comment]
I have switched `v5.x` to download files from GitHub. That should cover a few years worth of releases. Cloudsmith's `rabbitmq-server-all` (a direct download repository) only provisions [`3.8.14` plus](https://cloudsmith.io/~rabbitmq/repos/rabbitmq-server-all/packages/). GitHub should
be perfectly sufficient for `remote_file` resources.

Can you please update and try with `3.8.17`? I suspect that `3.8.1` could be used due to a typo or a Librarian/Berkshelf cache
entry?

Below is how I am testing this cookbook so that we are on the same page :)

## Test Kitchen

Assuming you have Docker running locally,

``` shell
export KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
kitchen test "default-deb-ubuntu-1804"
```

should provision a node and run some Test Kitchen tests using [these attributes](https://github.com/rabbitmq/chef-cookbook/blob/v5.x/.kitchen.dokken.yml#L137-L170) on Ubuntu 18.04.

The above succeeds for me. To make sure it does use GitHub for downloads, I modify the URL to be incorrect, and
the above test fails as expected.

## Vagrant

We have a [Vagrant-based test repository](https://github.com/rabbitmq/chef-cookbook-examples) that needs updating.
Currently it fails for me with a `VBoxManage startvm` error which I cannot immediately explain. Perhaps I need to upgrade Vagrant and VirtualBox.

I'll try again when I'm near a decent Internet connection again.

**Comment by michaelklishin** [comment]
Ah, I see your above comment. Thanks for the confirmation. 

This issue helped me realise that relying on Cloudsmith entirely at the moment would not be very wise. So it definitely spared the users of older version some head scratching 💚
